# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Dell.CommandConfigure
PackageVersion: 5.1.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
ProductCode: '{DF3680A9-B4C6-48D1-ACEF-0FF004446314}'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.dell.com/FOLDER12409577M/4/Dell-Command-Configure-Application_438RH_WIN64_5.0.1.3_A00.EXE
  InstallerSha256: 8013684C1A6C30509590AD96041CC82D37C08D1F43C337A221F5EE30F3D0892E
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-02-27
